### ISSUE TITLE
Drop rustc-serialize dependency

### ISSUE THREAD

**Issue by dtolnay** [autodidaddict/retroboard#1]
It has been deprecated: [announcement](https://users.rust-lang.org/t/deprecation-of-rustc-serialize/10485?u=dtolnay).

Is there any functionality you would require from another library before this would be possible?

**Comment by autodidaddict** [comment]
I'm still getting my feet wet with Rust and had no idea it was deprecated - it was the first example of json decoding I saw on google. I'll change it.

**Comment by autodidaddict** [comment]
Thanks @dtolnay for pointing this out.
